[profile.default]
solc = '0.8.19'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3

[fuzz]
runs = 50

[profile.optimized]
optimizer_runs = 10_000
via_ir = true
bytecode_hash = 'none'
out = 'optimized-out'
