[profile.default]
solc = '0.8.19'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
bytecode_hash = 'none'

[fuzz]
runs = 50

[profile.optimized]
optimizer_runs = 1_000_000
via_ir = true
out = 'optimized-out'

[profile.intense.fuzz]
runs = 10000
