[profile.default]
solc = '0.8.20'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
bytecode_hash = 'none'
gas_reports = ["Book", "Page"]
optimizer = false
via_ir = false

[fuzz]
runs = 512

[invariant]
runs = 2048
depth = 60
fail_on_revert = false

[profile.optimized]
optimizer = true
optimizer_runs = 4_294_967_295
via_ir = true
out = 'optimized-out'

[profile.optimized.fuzz]
runs = 64

[profile.optimized.invariant]
runs = 128
depth = 30
fail_on_revert = false
