[profile.default]
solc = '0.8.20'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
bytecode_hash = 'none'
gas_reports = ["Book", "Page"]
optimizer = false
via_ir = false

[fuzz]
runs = 50

[profile.optimized]
optimizer = true
optimizer_runs = 4_294_967_295
via_ir = true
out = 'optimized-out'

[profile.intense.fuzz]
runs = 10000
